### ISSUE TITLE
Old version on npm registry

### ISSUE THREAD

**Issue by PTihomir** [rebem/rebem-jsx#2]
Hi

What are the plans, when will you push the current version on github (0.3.0) to npm registry (0.2.1)?
I tried to install directly from github, but you did not push the `build` folder there.
I need the newer version, with newer `rebem-classname`, because I need to set the delimiters.

Thanks

**Comment by mistadikay** [comment]
@PTihomir just published. Sorry about that

**Comment by PTihomir** [comment]
@mistadikay Thanks for the quick response :)
