### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by dayAlone** [rebem/rebem-jsx#3]
![2016-07-05 18 34 38](https://cloud.githubusercontent.com/assets/4610649/16583372/33bd08d4-42df-11e6-873f-5eea9127c401.png)

I have this warnings, any chance to remove them?

**Comment by mistadikay** [comment]
@dayAlone please check version 0.3.1 — it should be fixed there

**Comment by dayAlone** [comment]
@mistadikay Thank you, but I have new error:)
<img width="818" alt="2016-07-06 18 09 41" src="https://cloud.githubusercontent.com/assets/4610649/16616067/fcf7e050-43a4-11e6-80a5-26bb4cf35476.png">

**Comment by mistadikay** [comment]
@dayAlone shit, I'm a retard. :) Fixed in 0.3.2

**Comment by deepsweet** [comment]
> shit, I'm a retard

:point_up:

**Comment by dayAlone** [comment]
@mistadikay @deepsweet thx! 👍
