### ISSUE TITLE
Add inheriting the parent block

### ISSUE THREAD

**Issue by a-x-** [rebem/rebem-jsx#4]
I want use it like this:

``` js
<div block="button">
  <span elem="text">{props.children || props.text}</span>
</div>
```

Current api is not cool, because `className="button__text"` is more short and simple than `block="button" elem="text"`

Is it possible?

**Comment by deepsweet** [comment]
> is more short and simple

the main (and the only) goal is to have an abstraction over raw classnames.

> Is it possible?

not at this moment. we have to think twice before implementing any inheritance because it has too many pitfalls.

**Comment by a-x-** [comment]
ok,

our [`bem-xjst`](https://github.com/bem/bem-xjst) `bemjson` template engine supports inheritance and it does not cause serious problems AFAIK

**Comment by mistadikay** [comment]
Neither React, nor JSX are template engines. You should probably try raw React first and read its documentation

**Comment by a-x-** [comment]
lol, ok)
